package main

const (
	ReqMove          = "MOVE"
	ReqAuthToken     = "AUTH_TOKEN"
	ReqGetState      = "GET_STATE"
	ReqGetHistory    = "GET_HISTORY"
	ReqListEntities  = "LIST_ENTITIES"
	ReqSkillTree     = "SKILL_TREE"
	ReqLearnSkill    = "LEARN_SKILL"
	ReqEnterWorld    = "ENTER_WORLD"
	ReqTalkNPC       = "TALK_NPC"
	ReqAcceptQuest   = "ACCEPT_QUEST"
	ReqCompleteQuest = "COMPLETE_QUEST"
	ReqAttack        = "ATTACK"
	ReqAttackMob     = "ATTACK_MOB"
	ReqAttackPVP     = "ATTACK_PVP"
	ReqRecoverCorpse = "RECOVER_CORPSE"
	ReqSetElement    = "SET_ELEMENT"
	ReqSummonPet     = "SUMMON_PET"
	ReqRecruitMerc   = "RECRUIT_MERC"
	ReqEquipItem     = "EQUIP_ITEM"
)

const (
	RespAuthRequired      = "AUTH_REQUIRED"
	RespRateLimited       = "RATE_LIMITED"
	RespError             = "ERROR"
	RespMoveRejected      = "MOVE_REJECTED"
	RespMoveOK            = "MOVE_OK"
	RespState             = "STATE"
	RespHistory           = "HISTORY"
	RespEntities          = "ENTITIES"
	RespSkillTree         = "SKILL_TREE"
	RespSkillRejected     = "SKILL_REJECTED"
	RespSkillLearned      = "SKILL_LEARNED"
	RespEnterDenied       = "ENTER_DENIED"
	RespEnterOK           = "ENTER_OK"
	RespNPCState          = "NPC_STATE"
	RespQuestRejected     = "QUEST_REJECTED"
	RespQuestAccepted     = "QUEST_ACCEPTED"
	RespQuestCompleted    = "QUEST_COMPLETED"
	RespPlayerDied        = "PLAYER_DIED"
	RespCombatResult      = "COMBAT_RESULT"
	RespMobAttackRejected = "MOB_ATTACK_REJECTED"
	RespMobAttackResult   = "MOB_ATTACK_RESULT"
	RespPVPRejected       = "PVP_REJECTED"
	RespPVPResult         = "PVP_RESULT"
	RespPVPHit            = "PVP_HIT"
	RespCorpseRecovery    = "CORPSE_RECOVERY"
	RespElementRejected   = "ELEMENT_REJECTED"
	RespElementSet        = "ELEMENT_SET"
	RespPetSummoned       = "PET_SUMMONED"
	RespMercRecruited     = "MERC_RECRUITED"
	RespEquipOK           = "EQUIP_OK"
	RespEquipRejected     = "EQUIP_REJECTED"
	RespAuthLocked        = "AUTH_LOCKED"
	RespAuthRejected      = "AUTH_REJECTED"
	RespAuthOK            = "AUTH_OK"
	RespPlayerJoined      = "PLAYER_JOINED"
	RespPlayerLeft        = "PLAYER_LEFT"
	RespPlayerMoved       = "PLAYER_MOVED"
)

const (
	MsgLoginRequired       = "LOGIN_REQUIRED"
	MsgTooManyRequests     = "TOO_MANY_REQUESTS"
	MsgTooManyAuthFailures = "TOO_MANY_AUTH_FAILURES"
	MsgUnknownCommand      = "UNKNOWN_COMMAND"
)
