package main

import (
	"context"
	"encoding/json"
	"log"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/go-redis/redis/v8"
)

var rdb *redis.Client
var redisCtx = context.Background()

const RedisEventBus = "zoneserver:event_bus"
const redisPresenceKeyPrefix = "zoneserver:presence:"

const redisPresenceTTL = 90 * time.Second

// Event Types
const (
	EvtChatSay     = "CHAT_SAY"
	EvtChatWorld   = "CHAT_WORLD"
	EvtChatWhisper = "CHAT_WHISPER"
	EvtChatGuild   = "CHAT_GUILD"
	EvtChatParty   = "CHAT_PARTY"
	EvtSocialSync  = "SOCIAL_SYNC"
	EvtDirectMsg   = "DIRECT_MESSAGE"
)

type RedisEvent struct {
	Type    string      `json:"type"`
	Payload interface{} `json:"payload"`
}

type ChatSayPayload struct {
	From    string  `json:"from"`
	WorldID int     `json:"world_id"`
	World   string  `json:"world"`
	Message string  `json:"message"`
	Ts      string  `json:"ts"`
	X       float64 `json:"x"`
	Y       float64 `json:"y"`
	Z       float64 `json:"z"`
}

type ChatWorldPayload struct {
	From    string `json:"from"`
	WorldID int    `json:"world_id"`
	World   string `json:"world"`
	Message string `json:"message"`
	Ts      string `json:"ts"`
}

type ChatWhisperPayload struct {
	From    string `json:"from"`
	To      string `json:"to"`
	Message string `json:"message"`
	Ts      string `json:"ts"`
}

type ChatGuildPayload struct {
	From    string `json:"from"`
	Guild   string `json:"guild"`
	Message string `json:"message"`
	Ts      string `json:"ts"`
}

type ChatPartyPayload struct {
	From    string `json:"from"`
	PartyID string `json:"party_id"`
	Message string `json:"message"`
	Ts      string `json:"ts"`
}

type SocialSyncPayload struct {
	Action string `json:"action"` // e.g., "PARTY_UPDATE", "GUILD_UPDATE"

	// Optionally include the mutated entities to replace in local cache
	Party       *Party       `json:"party,omitempty"`
	Guild       *Guild       `json:"guild,omitempty"`
	PartyInvite *PartyInvite `json:"party_invite,omitempty"`
	GuildInvite *GuildInvite `json:"guild_invite,omitempty"`
	Target      string       `json:"target,omitempty"`   // User targeted by the invite
	Removals    []string     `json:"removals,omitempty"` // Keys to remove
}

type DirectMessagePayload struct {
	Target  string        `json:"target"`
	Message ServerMessage `json:"message"`
}

var serverInstanceID = time.Now().UnixNano()

func InitRedis() {
	addr := redisAddr()
	client := redis.NewClient(&redis.Options{
		Addr:     addr,
		Password: "", // no password set
		DB:       0,  // use default DB
	})

	_, err := client.Ping(redisCtx).Result()
	if err != nil {
		log.Printf("Warning: Failed to connect to Redis at %s: %v", addr, err)
		log.Printf("Running in local-only mode for messaging.")
		rdb = nil
		return
	}
	rdb = client
	log.Println("Connected to Redis Pub/Sub successfully.")

	go listenToRedisBus()
}

func redisAddr() string {
	if addr := strings.TrimSpace(os.Getenv("A3_REDIS_ADDR")); addr != "" {
		return addr
	}
	return "127.0.0.1:6379"
}

func PublishRedisEvent(eventType string, payload interface{}) {
	if rdb == nil {
		// Fallback to local routing if redis is missing
		routeEventLocally(RedisEvent{Type: eventType, Payload: payload}, true)
		return
	}
	evt := RedisEvent{Type: eventType, Payload: payload}
	data, _ := json.Marshal(evt)
	rdb.Publish(redisCtx, RedisEventBus, data)
}

func listenToRedisBus() {
	if rdb == nil {
		return
	}
	pubsub := rdb.Subscribe(redisCtx, RedisEventBus)
	defer pubsub.Close()
	ch := pubsub.Channel()

	for msg := range ch {
		var evt RedisEvent
		if err := json.Unmarshal([]byte(msg.Payload), &evt); err == nil {
			routeEventLocally(evt, false)
		}
	}
}

func routeEventLocally(evt RedisEvent, isLocalFallback bool) {
	// Re-marshal and unmarshal payload to specific types so we can strictly type check
	data, _ := json.Marshal(evt.Payload)

	switch evt.Type {
	case EvtChatSay:
		var p ChatSayPayload
		json.Unmarshal(data, &p)
		handleChatSayEvent(p)
	case EvtChatWorld:
		var p ChatWorldPayload
		json.Unmarshal(data, &p)
		handleChatWorldEvent(p)
	case EvtChatWhisper:
		var p ChatWhisperPayload
		json.Unmarshal(data, &p)
		handleChatWhisperEvent(p)
	case EvtChatGuild:
		var p ChatGuildPayload
		json.Unmarshal(data, &p)
		handleChatGuildEvent(p)
	case EvtChatParty:
		var p ChatPartyPayload
		json.Unmarshal(data, &p)
		handleChatPartyEvent(p)
	case EvtSocialSync:
		// We ignore social syncs generated by our own process if doing local fallback
		if isLocalFallback {
			return
		}
		var p SocialSyncPayload
		json.Unmarshal(data, &p)
		handleSocialSyncEvent(p)
	case EvtDirectMsg:
		var p DirectMessagePayload
		json.Unmarshal(data, &p)
		handleDirectMessageEvent(p)
	}
}

func handleChatSayEvent(p ChatSayPayload) {
	msgPayload := map[string]interface{}{
		"channel": "say",
		"from":    p.From,
		"world":   p.World,
		"message": p.Message,
		"ts":      p.Ts,
	}
	senderPos := Position{X: p.X, Y: p.Y, Z: p.Z}
	worldID := WorldID(p.WorldID)

	forEachSession(func(other *ClientSession) {
		if !other.Authenticated || other.Character == nil || other.World == nil {
			return
		}
		if other.World.ID != worldID {
			return
		}
		if other.Character.Name != p.From && !isBlocked(other.Character.Name, p.From) {
			if !isVisible(senderPos, other.Position) {
				return
			}
			sendMessage(other.Conn, ServerMessage{Command: RespChatMessage, Payload: msgPayload})
		}
		// Also send to the sender if they are on this server
		if other.Character.Name == p.From {
			sendMessage(other.Conn, ServerMessage{Command: RespChatMessage, Payload: msgPayload})
		}
	})
}

func handleChatWorldEvent(p ChatWorldPayload) {
	msgPayload := map[string]interface{}{
		"channel": "world",
		"from":    p.From,
		"world":   p.World,
		"message": p.Message,
		"ts":      p.Ts,
	}
	worldID := WorldID(p.WorldID)

	forEachSession(func(other *ClientSession) {
		if !other.Authenticated || other.Character == nil || other.World == nil {
			return
		}
		if other.World.ID != worldID {
			return
		}
		// don't send to blocked
		if other.Character.Name != p.From && isBlocked(other.Character.Name, p.From) {
			return
		}
		sendMessage(other.Conn, ServerMessage{Command: RespChatMessage, Payload: msgPayload})
	})
}

func handleChatWhisperEvent(p ChatWhisperPayload) {
	msgPayload := map[string]interface{}{
		"channel": "whisper",
		"from":    p.From,
		"to":      p.To,
		"message": p.Message,
		"ts":      p.Ts,
	}

	forEachSession(func(other *ClientSession) {
		if !other.Authenticated || other.Character == nil {
			return
		}
		if other.Character.Name == p.To || other.Character.Name == p.From {
			sendMessage(other.Conn, ServerMessage{Command: RespChatMessage, Payload: msgPayload})
		}
	})
}

func handleChatGuildEvent(p ChatGuildPayload) {
	msgPayload := map[string]interface{}{
		"channel": "guild",
		"from":    p.From,
		"guild":   p.Guild,
		"message": p.Message,
		"ts":      p.Ts,
	}

	forEachSession(func(other *ClientSession) {
		if !other.Authenticated || other.Character == nil {
			return
		}
		if other.Character.Guild == p.Guild {
			if other.Character.Name != p.From && isBlocked(other.Character.Name, p.From) {
				return
			}
			sendMessage(other.Conn, ServerMessage{Command: RespChatMessage, Payload: msgPayload})
		}
	})
}

func handleChatPartyEvent(p ChatPartyPayload) {
	msgPayload := map[string]interface{}{
		"channel": "party",
		"from":    p.From,
		"message": p.Message,
		"ts":      p.Ts,
	}

	partyMu.RLock()
	party := parties[p.PartyID]
	partyMu.RUnlock()

	if party == nil {
		return
	}

	forEachSession(func(other *ClientSession) {
		if !other.Authenticated || other.Character == nil {
			return
		}
		if party.Members[other.Character.Name] {
			if other.Character.Name != p.From && isBlocked(other.Character.Name, p.From) {
				return
			}
			sendMessage(other.Conn, ServerMessage{Command: RespChatMessage, Payload: msgPayload})
		}
	})
}

// Global Mutex block during sync to avoid concurrent map writes
var socialSyncMu sync.Mutex

func handleSocialSyncEvent(p SocialSyncPayload) {
	socialSyncMu.Lock()
	defer socialSyncMu.Unlock()

	switch p.Action {
	case "PARTY_UPDATE":
		partyMu.Lock()
		if p.Party != nil {
			parties[p.Party.ID] = p.Party
			for member := range p.Party.Members {
				partyByMember[member] = p.Party.ID
			}
		}
		for _, member := range p.Removals {
			delete(partyByMember, member)
		}
		if p.Party != nil && len(p.Party.Members) == 0 {
			delete(parties, p.Party.ID)
		}
		partyMu.Unlock()
	case "PARTY_DISBAND":
		partyMu.Lock()
		if p.Party != nil {
			delete(parties, p.Party.ID)
		}
		for _, member := range p.Removals {
			delete(partyByMember, member)
		}
		partyMu.Unlock()
	case "PARTY_INVITE_SET":
		partyMu.Lock()
		if p.Target != "" && p.PartyInvite != nil {
			partyInvites[p.Target] = *p.PartyInvite
		}
		partyMu.Unlock()
	case "PARTY_INVITE_CLEAR":
		partyMu.Lock()
		if p.Target != "" {
			delete(partyInvites, p.Target)
		}
		partyMu.Unlock()
	case "GUILD_UPDATE":
		guildMu.Lock()
		if p.Guild != nil {
			guilds[p.Guild.Name] = p.Guild
		}
		if len(p.Removals) > 0 {
			for _, guildName := range p.Removals {
				delete(guilds, guildName)
			}
		}
		guildMu.Unlock()
		reconcileLocalGuildState()
	case "GUILD_INVITE_SET":
		guildMu.Lock()
		if p.Target != "" && p.GuildInvite != nil {
			guildInvites[p.Target] = *p.GuildInvite
		}
		guildMu.Unlock()
	case "GUILD_INVITE_CLEAR":
		guildMu.Lock()
		if p.Target != "" {
			delete(guildInvites, p.Target)
		}
		guildMu.Unlock()
	case "GUILD_DISBAND":
		guildMu.Lock()
		if len(p.Removals) > 0 {
			for _, guildName := range p.Removals {
				delete(guilds, guildName)
			}
		} else if p.Guild != nil {
			delete(guilds, p.Guild.Name)
		}
		guildMu.Unlock()
		reconcileLocalGuildState()
	}
}

func BroadcastSocialSync(p SocialSyncPayload) {
	PublishRedisEvent(EvtSocialSync, p)
}

func handleDirectMessageEvent(p DirectMessagePayload) {
	target := strings.TrimSpace(p.Target)
	if target == "" {
		return
	}
	session := findSessionByCharacterName(target)
	if session == nil || !session.Authenticated || session.Character == nil {
		return
	}
	sendMessage(session.Conn, p.Message)
}

func sendMessageToCharacter(name string, msg ServerMessage) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return false
	}
	if session := findSessionByCharacterName(name); session != nil && session.Authenticated && session.Character != nil {
		sendMessage(session.Conn, msg)
		return true
	}
	if rdb == nil {
		return false
	}
	PublishRedisEvent(EvtDirectMsg, DirectMessagePayload{Target: name, Message: msg})
	return true
}

func presenceRedisKey(name string) string {
	return redisPresenceKeyPrefix + sanitizeCharacterName(name)
}

func markCharacterOnline(name string) {
	name = strings.TrimSpace(name)
	if name == "" || rdb == nil {
		return
	}
	key := presenceRedisKey(name)
	if err := rdb.SAdd(redisCtx, key, serverInstanceID).Err(); err != nil {
		log.Printf("failed to mark %q online in redis: %v", name, err)
		return
	}
	if err := rdb.Expire(redisCtx, key, redisPresenceTTL).Err(); err != nil {
		log.Printf("failed to refresh presence ttl for %q: %v", name, err)
	}
}

func markCharacterOffline(name string) {
	name = strings.TrimSpace(name)
	if name == "" || rdb == nil {
		return
	}
	key := presenceRedisKey(name)
	if err := rdb.SRem(redisCtx, key, serverInstanceID).Err(); err != nil {
		log.Printf("failed to mark %q offline in redis: %v", name, err)
		return
	}
	count, err := rdb.SCard(redisCtx, key).Result()
	if err == nil && count == 0 {
		_ = rdb.Del(redisCtx, key).Err()
	}
}

func refreshRedisPresence() {
	if rdb == nil {
		return
	}
	forEachSession(func(session *ClientSession) {
		if session == nil || !session.Authenticated || session.Character == nil {
			return
		}
		markCharacterOnline(session.Character.Name)
	})
}

func isCharacterOnlineAnywhere(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return false
	}
	if session := findSessionByCharacterName(name); session != nil && session.Authenticated && session.Character != nil {
		return true
	}
	if rdb == nil {
		return false
	}
	count, err := rdb.SCard(redisCtx, presenceRedisKey(name)).Result()
	if err != nil {
		log.Printf("failed to query redis presence for %q: %v", name, err)
		return false
	}
	return count > 0
}
