package main

func statePayload(s *ClientSession) map[string]interface{} {
	c := s.Character
	return map[string]interface{}{
		"name":         c.Name,
		"class":        c.Class,
		"strength":     c.Strength,
		"dexterity":    c.Dexterity,
		"level":        c.Level,
		"xp":           c.XP,
		"xp_debt":      c.XPDebt,
		"hp":           c.HP,
		"max_hp":       c.MaxHP,
		"aura_level":   c.AuraLevel,
		"world":        s.World.Name,
		"position":     s.Position,
		"trust":        c.Trust,
		"quests":       c.Quests,
		"pet":          c.Pet,
		"mercenary":    c.Mercenary,
		"elemental":    c.Elemental,
		"presence":     canonicalPresenceStatus(c.Presence),
		"skill_points": c.SkillPoints,
		"skills":       c.Skills,
		"pk_score":     c.PKScore,
		"honor":        c.Honor,
		"inventory":    c.Inventory,
		"materials":    c.Materials,
		"storage":      c.Storage,
		"gold":         c.Gold,
		"wallet_gold":  c.WalletGold,
		"friends":      friendNamesForCharacter(c),
		"blocked":      blockNamesForCharacter(c),
		"equipped":     c.Equipped,
		"corpse":       c.Corpse,
		"history":      getUnlockHistoryPayload(),
		"guild":        c.Guild,
		"guild_role":   c.GuildRole,
		"party":        partySnapshotForCharacter(c.Name),
	}
}
